pipeline {
    agent any

    stages {
        stage('clone') {
            steps {
                git url : 'https://github.com/Diovane1103/TemaFinal1.git'
            }
        }
        stage('build') {
            steps {
                sh 'gradle clean build'
            }
        }
        stage('Jenkins') {
            steps {
                sh 'curl -uadmin:AP5MhsmLzDkCkV4mrwzXgzLpgGz -O "http://localhost:8081/artifactory/repo/hello.war"'
            }
        }
        stage ('Packer') {
            steps {
                sh 'packer build Packer.json'
            }
        }
    }
}
